### ISSUE TITLE
Use -like instead of -eq

### ISSUE THREAD

**Issue by fmms** [sabinio/salt#19]
Hi,

in https://github.com/sabinio/salt/blob/master/salt/functions/GetSqlAgentAsXml.ps1#L41 using a like allows to extract all jobs starting with a prefix, which is very usefully in bigger environments.

Creating an issue, as I currently cannot do the Pull request.

regards

**Comment by RichieBzzzt** [comment]
Hello! 

I’ll take a look: I’m sure that the change won’t break any other teams using it, but will want to test it first.

**Comment by RichieBzzzt** [comment]
Merged as part of #23
