### ISSUE TITLE
SSIS environment reference must be optional

### ISSUE THREAD

**Issue by fmms** [sabinio/salt#21]
Hi,

the script throws an exception in case one has an SSIS step configured without an environment reference.
https://github.com/sabinio/salt/blob/master/salt/functions/GetSqlAgentAsXml.ps1#L183

```
Ausnahme beim Aufrufen von "ExecuteScalar" mit 1 Argument(en):  "An exception occurred while executing a Transact-SQL statement or batch."
In Zeile:187 Zeichen:21
+ ...             $ssisEnvironment = $SqlServer.ConnectionContext.ExecuteSc ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExecutionFailureException
````

This is because we are trying to exceute the following SQL statement:
```
 SELECT [environment_name]
             FROM [SSISDB].[catalog].[environment_references] er
             WHERE er.reference_id =
```

notice the missing id after the equals sign.

**Comment by RichieBzzzt** [comment]
Ok I have done this as part of #24 . An extracted xml file that doesn't have an environment reference can also be imported.
